### ISSUE TITLE
Fix of crash in async functions that throw unhandled errors

### ISSUE THREAD

**Issue by c-smile** [saghul/txiki.js#164]
[This change](https://github.com/c-smile/txiki.js/commit/2c7ca3ecfcb07df28ab31f3ad223b77d39b8fdae) will fix crash on this code:
```JavaScript
  async showDir() {
    let list = await sys.fs.readdir("non existent path");
    for await (const file of list) 
      console.log(file);
  } 
```
Note that this code 
```JavaScript
  async showDir() {
    try {
      let list = await sys.fs.readdir("non existent path");
      for await (const file of list) 
        console.log(file);
    } catch(e) {  }
  } 
```
works OK.

**Comment by saghul** [comment]
Hey there, sorry for the delay. I don't see the problem here. In the first version you have an unhandled rejection, unless you catch it in the caller side.

Full example:

```
async function showDir() {
    let list = await tjs.fs.readdir("non existent path");
    for await (const file of list)
        console.log(file);
}

(async () => {
    await showDir();
})();

```

```
$ ./build/tjs t.js
Unhandled promise rejection: Error: no such file or directory
    at showDir (t.js:3)
```

The proposed fix is not correct because throwing the error is done with `tjs_throw_errno`, otherwise it would throw errors twice, since `tjs_throw_errno` calls `tjs_new_error`.
