### ISSUE TITLE
WebAssembly.Instance.exports missing memory property 

### ISSUE THREAD

**Issue by ahaoboy** [saghul/txiki.js#629]
I want to try to use txiki to run a wasm image processing program, but I encounter some problems. I am not sure whether it is a bug in txiki or wasm3.

https://github.com/ahaoboy/txiki-wasm-bench/blob/main/src/image.ts

build and run with tjs, and you will get an error `TypeError: cannot read property 'buffer' of undefined`
Below is the output of node and tjs, tjs lacks the memory property and has an additional <unnamed> property

```
wasm = instance.exports;

cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
```

node
```
wasm [
  'memory',
  '__wbg_image_free',
  '__wbg_get_image_width',
  '__wbg_set_image_width',
  '__wbg_get_image_height',
  '__wbg_set_image_height',
  '__wbg_get_image_channel',
  '__wbg_set_image_channel',
  'image_pixels',
  'decode',
  '__wbindgen_add_to_stack_pointer',
  '__wbindgen_free',
  '__wbindgen_malloc'
]
```

```
[
 '__wbindgen_throw',
  '<unnamed>',
  'image_pixels',
  'decode',
  '__wbindgen_malloc',
  '__wbg_image_free',
  '__wbg_set_image_width',
  '__wbg_set_image_height',
  '__wbg_set_image_channel',
  '__wbg_get_image_width',
  '__wbg_get_image_height',
  '__wbg_get_image_channel',
  '__wbindgen_free',
  '__wbindgen_add_to_stack_pointer'
]
```

**Comment by saghul** [comment]
WASM Memory is not supported at the moment.

Not sure wasm3 exposes it, but alas its development is pretty much stalled so don't hold your breadth on this one 😅

**Comment by ahaoboy** [comment]
Would you consider using wasmtime to support wasm? The performance of wasmtime is much faster than wasm3, almost reaching the speed of v8 wasm, but the size and code complexity are also very large.

**Comment by KaruroChori** [comment]
If changes of the runtime are on the table I think https://github.com/bytecodealliance/wasm-micro-runtime would be a better fit.  
It is mostly written in C, not rust, making it more in line with the rest of this project. It is designed to operate on embedded systems. As such it has a small footprint, while having a much better and wider support for official specs and further extensions compared to wasm3.

Also wasm3 has halted its development due to the personal circumstances of the author, so it is unlikely we will ever see new features implemented.

**Comment by ahaoboy** [comment]
> If changes of the runtime are on the table I think https://github.com/bytecodealliance/wasm-micro-runtime would be a better fit.



Although wasmtime also has [Embedding in C](https://docs.wasmtime.dev/lang-c.html#embedding-in-c), its size is too large, perhaps as much as 10mb, while WAMR seems to be less than 100k?

**Comment by KaruroChori** [comment]
I implicitly assumed it was embeddable in C, the problem would be the hard requirement to have the rust toolchain installed in order to build txiki. @saghul is distributing the compiled c bundles derived from JS as part of the repo (`make js`) to prevent people from needing npm installed on their system. I think a hard dependency with rust would be out of question.

Yes, that should be about its size taking into account all parts and libraries, some of which are optional.

**Comment by saghul** [comment]
Spot on!
